`workdir`: Improve scripts and `README.md`
unikraft-upb/maintainer-tools pull request #4
Opened 2023-07-30 14:20 UTC by razvand

Improve usability in scripts according to verbal feedback. Also improve `README.md` accordingly.

2023-07-30 15:02 UTC, StefanJum requested changes

2023-07-30 15:02 UTC, StefanJum commented on workdir/README.md
>  ```
Add `console` here.

2023-07-30 15:02 UTC, StefanJum commented on workdir/README.md
>  ```
```suggestion
```text
```

2023-07-30 15:02 UTC, StefanJum commented on workdir/README.md
> +### Make-based Builds
```suggestion
### Make-based Applications
```

2023-07-30 15:02 UTC, StefanJum commented on workdir/README.md
> +### KraftKit-based Builds
```suggestion
### KraftKit-based Applications
```

2023-07-30 15:02 UTC, StefanJum commented on workdir/README.md
>  In `copy/common/` the files are common to all directories, and the copying is something like `for d in apps/*/; do cp copy/common/* "$d"; done`.
Add the `copy/common-nocopy/` directory here.

2023-08-01 09:33 UTC, StefanJum approved these changes
Looks fine to me, thank you.

2023-08-01 10:33 UTC, gabrielmocanu approved these changes
LGTM

2023-08-01 11:24 UTC, merged